version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.dockerfile
        ports:
            -   8098:80 # порты, из системы мы ообращаеися к nginx по пути http://localhost:8098 , а изнутри контейнера http://nginx:80
        volumes:
            - ./:/var/www/laravel-docker # вся текущая папка пробрасывается в контейнер по пути /var/www/laravel-docker
        links:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.dockerfile
        volumes:
            -   ./:/var/www/laravel-docker # вся текущая папка пробрасывается в контейнер по пути /var/www/laravel-docker
            - type: "bind" # пробрасываем папку /tmp в систему по адресу /tmp (для сохранения логов и профайлов xdebug)
              source: "/tmp"
              target: "/tmp"
        links:
            -   mysql
        ports:
            - "9000:9000"
            - "3000:3000" # дополнительный порт для вебпака/Vite 
    mysql:
        platform: linux/x86_64 # add for mac m1
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
        -   3306:3306 
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Europe/Kiev"
            #MYSQL_DATABASE: laravel
        volumes:
            - ./docker/mysql-data:/var/lib/mysql # Данные MYSQL будут хранится в папке /docker/mysql-data, если хотим использовать Том, то можно указать путь типа mysql-data:/var/lib/mysql
            #- mysql-data:/var/lib/mysql # том для хранения БД mysql-data будет создан в самом докере, если хотим хранить в папке на локальной машине, то можно указать путь типа ./mysql-data:/var/lib/mysql 

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql

volumes:
    mysql-data: # том для хранения БД, Если исполюзуется том в настройках mysql volumes:
